import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  BellOff,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleAlert,
  CircleUser,
  Clock,
  Columns3,
  Command,
  Copy,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  Globe,
  GripVertical,
  Heart,
  Home,
  Info,
  KeyRound,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  Monitor,
  Moon,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  X,
  XCircle,
  type IconNode,
} from 'lucide';

/**
 * Curated icon set. Only icons listed here end up in the bundle.
 * Names are kebab-case and stable — templates reference them as strings, so
 * renaming is a breaking change. Add new icons here; never import `lucide` in features.
 */
export const APP_ICONS = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  bell: Bell,
  'bell-off': BellOff,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'circle-user': CircleUser,
  clock: Clock,
  columns: Columns3,
  command: Command,
  copy: Copy,
  download: Download,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  filter: Filter,
  globe: Globe,
  'grip-vertical': GripVertical,
  heart: Heart,
  home: Home,
  info: Info,
  key: KeyRound,
  'layout-dashboard': LayoutDashboard,
  loader: Loader2,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  sliders: SlidersHorizontal,
  sun: Sun,
  trash: Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  x: X,
  'x-circle': XCircle,
} as const satisfies Readonly<Record<string, IconNode>>;

export type AppIconName = keyof typeof APP_ICONS;
